### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by peduxe** [rdepena/node-dualshock-controller#48]
I can't find a way to solve this, tried giving permissions to my user/usergroup with `chown` but no luck.

The error is the following when I run my JS file with node (6.6.0).

Although the controller is working well because the data is being logged on `/dev/input/js1` not `/dev/input/js0`. Is there a way I can choose wich joystick port it connects to?

```sh
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, open '/dev/input/js0'
    at Error (native)
`

**Comment by rdepena** [comment]
Just double checked the code and it does not allows the js# to be passed in, I will try to recreate this and see what a fix looks like.

**Comment by peduxe** [comment]
thank you, btw even when I try to get logs with `jstest` on js0 it doesn't log anything

**Comment by rdepena** [comment]
ahh cool. but yea will probably make the change. 

Thanks for reporting.

**Comment by rdepena** [comment]
Hey @peduxe as of version 0.6.10 (last night's build), you can give it the js index as part of the options called "linuxJoystickId", I have not figured out discovery yet.

**Comment by peduxe** [comment]
thank you :bow:
