### ISSUE TITLE
DS4: r2Analog stick not working

### ISSUE THREAD

**Issue by tobiasmuecksch** [rdepena/node-dualshock-controller#67]
Hey there,

I'm using the example from the readme and I've set the config value to `config: 'dualShock4',`.
Additionally I've added the following line:

```
controller.on('l2Analog:move', data => console.log('L2 Moved: ' + data.x));
```

When I move the L2 button nothing happens. It works for the two main sticks without a problem.

I've debugged the`src/analogs.js` file by adding the following to line 26:

```
        if (analogStick.name === 'r2Analog') {
            console.log('ANALOG', analogStick);

        }
```

With that console output I found out that `x` always has the value `101`. Even while moving it.

```
ANALOG { name: 'r2Analog', x: 101, joystickXNumber: 4 }
ANALOG { name: 'r2Analog', x: 101, joystickXNumber: 4 }
ANALOG { name: 'r2Analog', x: 101, joystickXNumber: 4 }
ANALOG { name: 'r2Analog', x: 101, joystickXNumber: 4 }
ANALOG { name: 'r2Analog', x: 101, joystickXNumber: 4 }
ANALOG { name: 'r2Analog', x: 101, joystickXNumber: 4 }
```

How can I debug that problem further?

**Comment by rdepena** [comment]
Hey @tobiasmuecksch , try running the [console print dualshock 4 example](https://github.com/rdepena/node-dualshock-controller/blob/master/examples/consolePrintDualShock4.js),  if you don't get any results with that you can try printing the raw hid output for that specific controller:

Use the config json file as a reference:
[Button block is the index on the data buffer] (https://github.com/rdepena/node-dualshock-controller/blob/master/controllerConfigurations/dualShock4.json#L46)

[Vendor and device id](https://github.com/rdepena/node-dualshock-controller/blob/master/controllerConfigurations/dualShock4.json#L2)

And modify [The device discovery help example](https://github.com/rdepena/node-dualshock-controller/blob/master/examples/deviceDiscoveryHelp.js#L8) to connect to that specific vendor/deviceId combo and print the specific index.

Also, do you get the same results if you are connected via USB?

**Comment by tobiasmuecksch** [comment]
With the `console print dualshock 4 example` you've mentioned, the L1 and R1 buttons work. Why - what is different in this example?

**Comment by tobiasmuecksch** [comment]
This is my source code:
https://gist.github.com/tobiasmuecksch/36962177b65ec8df39fc56fe44d35e55

**Comment by rdepena** [comment]
I guess lines 42 and 43 from the gist are the lines of interest: 

```javascript

controller.on('l2:move', data => console.log('L2 moved'));
controller.on('R2:move', data => console.log('R1 moved'));
```
I changed them to (capturing the 'analog' event):
```javascript
controller.on('l2:analog', data => console.log(data));
controller.on('r2:analog', data => console.log(data));
```

Let me know if that was not the issue.

**Comment by tobiasmuecksch** [comment]
@rdepena Thank you so much. Using `r2:analog` instead of `r2:move` solved the problem!

**Comment by rdepena** [comment]
@tobiasmuecksch cool, np.
